fix: Don't pass version_num to create_next_container_version
The original version of this code depended upon `version_num` being popped out
of `valid_published` before `valid_published` got expanded. A recent change
changed the argument order, leading to:

  TypeError: create_next_container_version() got an unexpected keyword argument
  'version_num'

whenever restoring an archive with any published containers. This commit
restores the original code's order of operations, but a bit more explicitly.

Bumps from 0.39.2 to 0.40.0 (it would be 0.39.3, but the previous
commit had breaking changes and neglected to bump the minor version)